
language: ruby
rvm:
- 2.2.0
# branch whitelist
branches:
  only:
  - master
# env:
#   global:
#   - secure: NIFnh3i0Ll2B6iEdEoQYvzNXOCiEySq69mzW/bY76LLJ92JKFqjl9Aazr+cY09QdsPF+pY/CSr/oLNs9Fh+nOQn8bB8XlTpSJS7welKlGsmCZCByfT7RP+oM4KfUm5PJ9XgNi9584Xh/S4r36Z0VzEcza/zWcEtntr1CdkKH70w=
#   - secure: Z/ANF7e4hNxb0ou6Kk6/G0sLO5G+Jv1r1586VIfiXgXGTiOgkkF/8jcjKl49ngbQiWWXFByupdGdjW9k8yi9Iy9goYeINzj+phO+UgdY3BJwOq0Fufd5E5/W9ppc+zAVFVXsjPzjjKNDZBURAq4uJ/J6oHEmd7FfzWUC6oktHMM=
install:
- sudo apt-get install python-dateutil
- wget https://github.com/s3tools/s3cmd/archive/v1.5.0-rc1.tar.gz
- tar -xzvf v1.5.0-rc1.tar.gz
- cd s3cmd-1.5.0-rc1 && sudo python setup.py install
- s3cmd --version
- bundle install
script:
- rake build
after_success:
- rake deploy:travis