
language: ruby
rvm:
- 2.2.0
# branch whitelist
branches:
  only:
  - master
install:
- bundle install
script:
- rake build:drafts
after_success:
- rake deploy:travisStaging
script:
- rake build
after_success:
- rake deploy:travisProduction