
language: ruby
rvm:
- 2.3.0
# branch whitelist
branches:
only:
- master
install:
- bundle install
script:
- rake build:drafts
- rake build
after_success:
- rake deploy:travis_staging
- rake deploy:travis_production
